data_source retail:
  type: bigquery
  connection:
    account_info_json_path: include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'airflow-dbt-pipeline'
    dataset: retail